name: my-workflow
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: create-release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.$(date +'%Y%m%d%H%M%S')
        release_name: Release v1.0.$(date +'%Y%m%d%H%M%S')
        body: |
          Changes in this Release
          - Feature 1
          - Feature 2
        draft: false
        prerelease: false
